### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by Phil-Friderici**
Hej @anders-larsson,

here is the code and readme refactor. Please check and merge.
I will then continue to add the anti-sort functionality of the open PR.

### CODE REVIEW

**Comment by anders-larsson** [comment]
Hi,
Thanks for your contributions as always and it looks good.

However I tried this on a system and it fails because ```$ticket_lifetime is not a string```.  but I cannot understand why. Currently it is Hiera as specified below and the value finds itself into krb5.conf.
```
krb5::ticket_lifetime: '24000'
```

It's working in version 0.7.1, there must be something in this pull request which I'm currently unable to understand.

**Comment by anders-larsson** [comment]
Error for completeness:
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: krb5::ticket_lifetime is not a string. at /etc/puppet/environments/testenv/modules/krb5/manifests/init.pp:38 on node mysystem.domain.tld```

**Comment by Phil-Friderici** [comment]
Thanks for the feedback, I'll look into this detail to fix it.

**Comment by anders-larsson** [comment]
Using `git bisect` I can also confirm it is commit https://github.com/kodguru/puppet-module-krb5/pull/24/commits/c225f0003b90c2d1c4bd94d4b1f01528045dcdd6 causing this which was what I would expected as well but might as well be thorough.

**Comment by anders-larsson** [comment]
Hi again,

I did some further investigation and it appears is_string fails if there are only digits within the string (auto converted to integer(?)). 
```
24000 fails
x24000 works
24000x works
```

**Comment by Phil-Friderici** [comment]
yepp made the same observation. Stupid is_string !
Prepering a workaround is_string atm...

**Comment by Phil-Friderici** [comment]
The workaround should do the trick. Let me upgrade the module to utilize stdlib 5.2.0.

**Comment by Phil-Friderici** [comment]
Should be fixed now, please retest in production to verify.
I haven't have any more to add to this PR.

**Comment by anders-larsson** [comment]
I can confirm that it works correctly with the workaround. Would you mind squashing some commits such as switching to stdlib 5.2.0 directly and maybe change commit `satisfy Phil` with something more descriptive? Thanks!

**Comment by Phil-Friderici** [comment]
et voilà

**Comment by anders-larsson** [comment]
Don't forget `Satisfy Phil` too!

**Comment by Phil-Friderici** [comment]
oh you need to click on the three dots ;)

**Comment by anders-larsson** [comment]
Ok. Looks good to me. Shall we have this merged then?

**Comment by Phil-Friderici** [comment]
yes please, this will start me weekend then 🍹

**Comment by anders-larsson** [comment]
Merged. Thanks!

**Comment by Phil-Friderici** [comment]
Thanks Anders, that's a great start into the weekend :)

**Pull request merged**
